### ISSUE TITLE
Boilerplate needs to be setup

### ISSUE THREAD

**Issue by ananddeb23** [ananddeb23/ShopSocialFrontEnd#1]
**What do we want?**
We need to set up a common boilerplate code for our front end and install packages to be used for routing and responsive layout

**How do we do it?**
We use the create react app to set up the basic boilerplate and then install necessary packages.

**How does the timeline look like?**
We aim to achieve the target by 26th Feb 2018.

**Comment by aditiverma1009** [comment]
Works fine. Go ahead..
