### ISSUE TITLE
Administrator console

### ISSUE THREAD

**Issue by ananddeb23** [ananddeb23/ShopSocialFrontEnd#2]
**What do we want**?
We need to set up the administrator console view for the admin to be able to add products by id and category. The administrator must also be able to remove products by id. There should also be a scope added to orders management for the admin.

**How do we do it?**
We create the components and link them to the corresponding backend api's. 

**How does the timeline look like?**
We aim to achieve the target by 29th Feb 2018.

**Comment by aditiverma1009** [comment]
Admin Console/Inventory working.
